name: Client side workflow
on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client
      - run: docker build -t mikesglks/client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mikesglks/client npm run test 
  push-to-dockerhub:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID}}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mikesglks/multi-client ./client
      - run: docker build -t mikesglks/multi-nginx ./nginx
      - run: docker build -t mikesglks/multi-server ./server
      - run: docker build -t mikesglks/multi-worker ./worker
      - run: docker push mikesglks/multi-client 
      - run: docker push mikesglks/multi-nginx
      - run: docker push mikesglks/multi-server
      - run: docker push mikesglks/multi-worker
